const employees = [
  {
    id: 1,
    firstName: 'Auberon',
    lastName: 'Martland',
    email: 'amartland0@desdev.cn',
    phone: '6417685762',
    salary: '$2738.63',
    birthDate: '1993-02-26',
    contract_type: 'part time',
    position: 'Human Resources Assistant I',
    createdAt: '2019-05-13',
    updatedAt: null,
    isActive: true,
    category: 'Marketing',
  },
  {
    id: 2,
    firstName: 'Harwilll',
    lastName: 'Schulze',
    email: 'hschulze1@clickbank.net',
    phone: '9253813928',
    salary: '$2678.20',
    birthDate: '1991-04-25',
    contract_type: 'full time',
    position: 'Editor',
    createdAt: '2018-12-16',
    updatedAt: null,
    isActive: true,
    category: 'Programming',
  },
  {
    id: 3,
    firstName: 'Clyve',
    lastName: 'Ginnally',
    email: 'cginnally2@ox.ac.uk',
    phone: '3958559393',
    salary: '$4045.07',
    birthDate: '1990-08-14',
    contract_type: 'full time',
    position: 'Librarian',
    createdAt: '2002-07-06',
    updatedAt: null,
    isActive: true,
    category: 'Design',
  },
  {
    id: 4,
    firstName: 'Shantee',
    lastName: 'Gergher',
    email: 'sgergher3@mapy.cz',
    phone: '6689709162',
    salary: '$4970.80',
    birthDate: '2000-12-13',
    contract_type: 'part time',
    position: 'Community Outreach Specialist',
    createdAt: '2014-06-20',
    updatedAt: null,
    isActive: true,
    category: 'Programming',
  },
  {
    id: 5,
    firstName: 'Emogene',
    lastName: 'Tripet',
    email: 'etripet4@lycos.com',
    phone: '8077354923',
    salary: '$3482.28',
    birthDate: '1998-11-26',
    contract_type: 'full time',
    position: 'Account Coordinator',
    createdAt: '2018-09-26',
    updatedAt: null,
    isActive: true,
    category: 'Design',
  },
];

export default employees;
